---
title: "select_phenotypes"
author: "Andrea Estandia"
date: "06/10/2025"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
source("./src/wm-gwas_source.R")
```

Read data
```{r}
samples <- read.csv(file.path(data_path, "dfs", "samples.csv"))

phenotypes <- read.csv(file.path(data_path, "dfs", "gwas_hatch_checks.csv")) %>%
  dplyr::select(egg_id, hatch_date) 

vcf_order <- read.csv(file.path(data_path, "dfs","vcf_order.csv"), header=F) %>%
  rename(IID=V1)
```

Join data
```{r}
phenotypes_clean <- phenotypes %>%
  filter(egg_id %in% samples$IID) %>%
  rename(IID = egg_id) %>%
  mutate(
    FID = sub("_.*", "", IID),                              
    hatch_date = as.numeric(difftime(dmy(hatch_date),
                                     as.Date("2025-03-20"),
                                     units = "days"))
  ) %>%
  select(FID, IID, hatch_date) 
```

Sort df by vcf order
```{r}
id_col <- names(vcf_order)[grepl("iid|id|sample", names(vcf_order), ignore.case = TRUE)][1]

vcf_ids <- as.character(vcf_order[[id_col]])
vcf_index <- tibble::tibble(IID = vcf_ids, .vcf_order = seq_along(vcf_ids))

phenotypes_clean <- phenotypes_clean %>%
  dplyr::mutate(IID = as.character(IID)) %>%
  dplyr::inner_join(vcf_index, by = "IID") %>%   # keeps only samples present in vcf_order
  dplyr::arrange(.vcf_order) %>%
  dplyr::select(-.vcf_order) %>%
  mutate(hatch_date_std = scale(hatch_date)[,1])
```

Write out
```{r}
write.table(
  phenotypes_clean,
  file.path(data_path, "dfs", "pheno.txt"),
  row.names = FALSE,
  quote = FALSE
)
```

Subset phenotypes by getting the closest to the median by family
```{r}
phenotypes_subset <- phenotypes_clean %>%
  group_by(FID) %>%
  mutate(median_hatch = median(hatch_date, na.rm = TRUE)) %>%
  slice_min(abs(hatch_date - median_hatch), n = 1) %>%
  slice(1) %>%
  ungroup() %>%
  select(FID, IID, hatch_date)

# write pheno in same order as .fam (no header)
write.table(
  phenotypes_subset,
  file.path(data_path, "dfs", "pheno_subset.txt"),
  row.names = FALSE,
  quote = FALSE
)

```

Obtain a phenotype from the residuals (how much they deviate from their family mean)
```{r}
# Fit covariates + family fixed
fit <- lm(hatch_date ~ 1 + factor(FID), data = phenotypes_clean)  # include your covariates
phenotypes_clean$resid <- resid(fit)

# Save residuals in GCTA pheno format: FID IID phenotype
write.table(
  phenotypes_clean,
  file.path(data_path, "dfs", "pheno_resid.txt"),
  row.names = FALSE,
  quote = FALSE
)


```

Create a dummy phenotype file
```{r}
phenotypes_dummy <- phenotypes_clean %>%
  mutate(dummy = round(pmin(pmax(rnorm(nrow(phenotypes_clean), mean = 17.5, sd = 7), 0), 35))) #%>% 
  #select(FID, IID, dummy)

write.table(
  phenotypes_dummy,
  file.path(data_path, "dfs", "pheno_dummy.txt"),
  row.names = FALSE,
  quote = FALSE
)
```

Set family as a covariate for GEMMA
```{r}
covariates <- phenotypes_clean %>%
  mutate(covar = as.numeric(as.factor(FID))) %>%
  select(covar)

write.table(
  covariates,
  file.path(data_path, "dfs", "covariates.txt"),
  row.names = FALSE,
  col.names = FALSE,
  quote = FALSE
)
```